[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask==2.0.1",
    "gunicorn==20.1.0",
    "python-dotenv==0.19.0"
]
